server:
  port: 9000
# docker 部署宿主主机地址
projrct:
  real-address: 49.235.110.134

spring:
  application:
    name: config
  # config 配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LovingLiuMeMe/loving-config
          username: lovingliu@126.com
          password: liubo1995828
          basedir: /Users/lovingliu/Desktop/project/loving_cloud/loving-config/basedir
    # 消息总线
    bus:
      enabled: true
      trace:
        enabled: true
  # rabbitMq 的配置 (下面是默认参数,参数一致可不写)
  rabbitmq:
    host: 49.235.110.134
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://49.235.110.134:1000/eureka
  instance:
    # instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    instance-id: ${spring.application.name}:${project.real-address}:${server.port}
    prefer-ip-address: true
management:
  # 暴露bus-refresh
  endpoints:
    web:
      exposure:
        include: "*"